name: pegma
description: "A free and cross-platform version of the classic Peg solitaire! Enjoy the timeless puzzle on your mobile device!"
publish_to: 'none'
version: 1.0.0+6

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  go_router: ^14.6.2
  flutter_svg: ^2.0.13
  share_plus: ^11.1.0
  url_launcher: ^6.3.1
  url_launcher_ios: ^6.3.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.4
  talker: ^5.0.0
  talker_riverpod_logger: ^5.0.0
  talker_flutter: ^5.0.0
  intl_utils: ^2.8.11
  gaimon: ^1.4.1
  sqflite: ^2.4.2
  path: ^1.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter_launcher_icons:
  android: "launcher_icon"
  image_path_ios: "assets/logo/logo-light.png"
  image_path_ios_dark_transparent: "assets/logo/logo-dark.png"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/logo/logo-light.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_foreground: "assets/logo/logo-light.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - lib/data/levels/

  fonts:
  - family: Pegma
    fonts:
      - asset: assets/fonts/pegma-app.ttf

flutter_intl:
  enabled: true
